"""
Django settings for edgecut project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-+cgv6sxt1c#*#2*^sy^+o$5*02ahz)x!-$ko9s(i%2yuz116y)'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:8000",
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'edgecut.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

                'core.context_processor.social_media_links',
                'core.context_processor.head_bar',
                'core.context_processor.contact_ways',


            ],
        },
    },
]

WSGI_APPLICATION = 'edgecut.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/
import os

STATIC_URL = '/static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'static')

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'staticfiles')
]

INSTAGRAM_URL = 'https://www.instagram.com/?locale=az_AZ'
TWITTER_URL = 'https://twitter.com/yourusername'
FACEBOOK_URL = 'https://www.facebook.com/?locale=az_AZ'
LINKEDIN = 'https://linkedin.com/?locale=az_AZ'

HOME_URL = 'http://localhost:8000/'
ABOUT_URL = 'http://localhost:8000/about'
FURNITURES_URL = 'http://localhost:8000/furniture'
BLOG_URL = 'http://localhost:8000/blog'
CONTACT_PAGE_URL = 'http://localhost:8000/contact'

CALL_URL = 'tel:+994501234567'
MAIL_URL = 'https://mail.google.com/mail/?view=cm&fs=1&to=vafakhanim.h@gmail.com'
LOCATION_URL = 'https://www.google.com/maps/place/Texnoera+Academy/@40.3835291,49.8080313,17z/data=!3m1!4b1!4m6!3m5!1s0x40307d7c858c8d33:0xe51ced2ed687d883!8m2!3d40.3835291!4d49.8106062!16s%2Fg%2F11s8fnrczx?entry=ttu&g_ep=EgoyMDI1MDMwNC4wIKXMDSoASAFQAw%3D%3D'

MEDIA_URL = '/edgecut_media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'edgecut_media')
# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = "vfa.xh05@gmail.com"
EMAIL_HOST_PASSWORD = "fjxv aqbq gada owdk"
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
